#!/bin/bash 
#SBATCH --partition=debug 

#SBATCH --qos=240c-1h_debug  
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=64
#SBATCH --mem=48G 
#SBATCH --job-name=”algo2” 
#SBATCH --output=JobName.%J.out 

#SBATCH --error=JobName.%J.err 
#SBATCH --mail-user=kbangeles@up.edu.ph
#SBATCH --mail-type=ALL 
 
echo "SLURM_JOBID="$SLURM_JOBID 
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST 
echo "SLURM_NNODES"=$SLURM_NNODES 
echo "SLURMTMPDIR="$SLURMTMPDIR 
echo "working directory = "$SLURM_SUBMIT_DIR 
 
# Place commands to load environment modules here 
module load python/3.9.7
 
# Set stack size to unlimited 
ulimit -s unlimited 
 
# MAIN 
srun python tests.py algo2 5
